//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirLineReservationSystemProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AirlineReservationEntities : DbContext
    {
        public AirlineReservationEntities()
            : base("name=AirlineReservationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_AircraftDetails> tbl_AircraftDetails { get; set; }
        public virtual DbSet<tbl_Airports> tbl_Airports { get; set; }
        public virtual DbSet<tbl_FlightDetails> tbl_FlightDetails { get; set; }
        public virtual DbSet<tblAdmin> tblAdmins { get; set; }
        public virtual DbSet<tblBooking> tblBookings { get; set; }
        public virtual DbSet<tblpassenger_table> tblpassenger_table { get; set; }
        public virtual DbSet<tblPayment> tblPayments { get; set; }
        public virtual DbSet<tblSeat> tblSeats { get; set; }
        public virtual DbSet<tblTicket_table> tblTicket_table { get; set; }
        public virtual DbSet<tblTrip> tblTrips { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
    
        public virtual ObjectResult<proc_DetailsConfirmation_Result> proc_DetailsConfirmation(string mBID)
        {
            var mBIDParameter = mBID != null ?
                new ObjectParameter("mBID", mBID) :
                new ObjectParameter("mBID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_DetailsConfirmation_Result>("proc_DetailsConfirmation", mBIDParameter);
        }
    
        public virtual int proc_UserRegisteration(string t, string f, string l, Nullable<System.DateTime> dob, string phone, string email, string pass)
        {
            var tParameter = t != null ?
                new ObjectParameter("t", t) :
                new ObjectParameter("t", typeof(string));
    
            var fParameter = f != null ?
                new ObjectParameter("f", f) :
                new ObjectParameter("f", typeof(string));
    
            var lParameter = l != null ?
                new ObjectParameter("l", l) :
                new ObjectParameter("l", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(System.DateTime));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_UserRegisteration", tParameter, fParameter, lParameter, dobParameter, phoneParameter, emailParameter, passParameter);
        }
    
        public virtual ObjectResult<proc_UserLogin_Result> proc_UserLogin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_UserLogin_Result>("proc_UserLogin");
        }
    
        public virtual ObjectResult<proc_AdminLogin_Result> proc_AdminLogin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_AdminLogin_Result>("proc_AdminLogin");
        }
    
        public virtual int proc_AddFlight(string td, string dp, string ap, string cabin, string ef, string bf, string ff, string status)
        {
            var tdParameter = td != null ?
                new ObjectParameter("td", td) :
                new ObjectParameter("td", typeof(string));
    
            var dpParameter = dp != null ?
                new ObjectParameter("dp", dp) :
                new ObjectParameter("dp", typeof(string));
    
            var apParameter = ap != null ?
                new ObjectParameter("ap", ap) :
                new ObjectParameter("ap", typeof(string));
    
            var cabinParameter = cabin != null ?
                new ObjectParameter("cabin", cabin) :
                new ObjectParameter("cabin", typeof(string));
    
            var efParameter = ef != null ?
                new ObjectParameter("ef", ef) :
                new ObjectParameter("ef", typeof(string));
    
            var bfParameter = bf != null ?
                new ObjectParameter("bf", bf) :
                new ObjectParameter("bf", typeof(string));
    
            var ffParameter = ff != null ?
                new ObjectParameter("ff", ff) :
                new ObjectParameter("ff", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_AddFlight", tdParameter, dpParameter, apParameter, cabinParameter, efParameter, bfParameter, ffParameter, statusParameter);
        }
    
        public virtual int proc_EditFlight(string fid, string status)
        {
            var fidParameter = fid != null ?
                new ObjectParameter("fid", fid) :
                new ObjectParameter("fid", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_EditFlight", fidParameter, statusParameter);
        }
    
        public virtual ObjectResult<proc_ShowFlight_Result> proc_ShowFlight()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_ShowFlight_Result>("proc_ShowFlight");
        }
    
        public virtual ObjectResult<proc_displaypassengers_Result> proc_displaypassengers(string uid)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_displaypassengers_Result>("proc_displaypassengers", uidParameter);
        }
    
        public virtual int proc_insertpassengers(string ticketID, string pname, string gender, string seatID, Nullable<int> age)
        {
            var ticketIDParameter = ticketID != null ?
                new ObjectParameter("TicketID", ticketID) :
                new ObjectParameter("TicketID", typeof(string));
    
            var pnameParameter = pname != null ?
                new ObjectParameter("Pname", pname) :
                new ObjectParameter("Pname", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var seatIDParameter = seatID != null ?
                new ObjectParameter("SeatID", seatID) :
                new ObjectParameter("SeatID", typeof(string));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("Age", age) :
                new ObjectParameter("Age", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_insertpassengers", ticketIDParameter, pnameParameter, genderParameter, seatIDParameter, ageParameter);
        }
    
        public virtual ObjectResult<proc_DetailsConfirmation1_Result> proc_DetailsConfirmation1(string mBID)
        {
            var mBIDParameter = mBID != null ?
                new ObjectParameter("mBID", mBID) :
                new ObjectParameter("mBID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_DetailsConfirmation1_Result>("proc_DetailsConfirmation1", mBIDParameter);
        }
    
        public virtual ObjectResult<proc_UserDetails_Result> proc_UserDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_UserDetails_Result>("proc_UserDetails");
        }
    
        public virtual int proc_UserRegisteration1(string t, string f, string l, Nullable<System.DateTime> dob, string phone, string email, string pass, string sec)
        {
            var tParameter = t != null ?
                new ObjectParameter("t", t) :
                new ObjectParameter("t", typeof(string));
    
            var fParameter = f != null ?
                new ObjectParameter("f", f) :
                new ObjectParameter("f", typeof(string));
    
            var lParameter = l != null ?
                new ObjectParameter("l", l) :
                new ObjectParameter("l", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(System.DateTime));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            var secParameter = sec != null ?
                new ObjectParameter("sec", sec) :
                new ObjectParameter("sec", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_UserRegisteration1", tParameter, fParameter, lParameter, dobParameter, phoneParameter, emailParameter, passParameter, secParameter);
        }
    
        public virtual ObjectResult<proc_UserDetails1_Result> proc_UserDetails1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_UserDetails1_Result>("proc_UserDetails1");
        }
    
        public virtual ObjectResult<proc_getUserByEmail_Result> proc_getUserByEmail(string email, string sec)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var secParameter = sec != null ?
                new ObjectParameter("sec", sec) :
                new ObjectParameter("sec", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_getUserByEmail_Result>("proc_getUserByEmail", emailParameter, secParameter);
        }
    
        public virtual int proc_updateUser(string email, string sec)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var secParameter = sec != null ?
                new ObjectParameter("sec", sec) :
                new ObjectParameter("sec", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_updateUser", emailParameter, secParameter);
        }
    
        public virtual int proc_updateUser1(string email, string pass)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_updateUser1", emailParameter, passParameter);
        }
    
        public virtual int proc_updateUser2(string email, string pass)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_updateUser2", emailParameter, passParameter);
        }
    
        public virtual int proc_Booking(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_Booking", userIDParameter);
        }
    
        public virtual ObjectResult<proc_FlightSelect_Result> proc_FlightSelect(string from, string to, Nullable<System.DateTime> deptdate, Nullable<System.DateTime> returndate, Nullable<int> passengerCount)
        {
            var fromParameter = from != null ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(string));
    
            var toParameter = to != null ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(string));
    
            var deptdateParameter = deptdate.HasValue ?
                new ObjectParameter("deptdate", deptdate) :
                new ObjectParameter("deptdate", typeof(System.DateTime));
    
            var returndateParameter = returndate.HasValue ?
                new ObjectParameter("returndate", returndate) :
                new ObjectParameter("returndate", typeof(System.DateTime));
    
            var passengerCountParameter = passengerCount.HasValue ?
                new ObjectParameter("PassengerCount", passengerCount) :
                new ObjectParameter("PassengerCount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_FlightSelect_Result>("proc_FlightSelect", fromParameter, toParameter, deptdateParameter, returndateParameter, passengerCountParameter);
        }
    
        public virtual ObjectResult<proc_GetBookings_Result> proc_GetBookings(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetBookings_Result>("proc_GetBookings", userIDParameter);
        }
    
        public virtual int proc_TicketBook(string bID, string tripID)
        {
            var bIDParameter = bID != null ?
                new ObjectParameter("BID", bID) :
                new ObjectParameter("BID", typeof(string));
    
            var tripIDParameter = tripID != null ?
                new ObjectParameter("TripID", tripID) :
                new ObjectParameter("TripID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_TicketBook", bIDParameter, tripIDParameter);
        }
    
        public virtual int addTrip(string flightID, string airplane_No, Nullable<System.DateTime> tripDate, Nullable<System.TimeSpan> depTime, Nullable<System.TimeSpan> arrival_Time)
        {
            var flightIDParameter = flightID != null ?
                new ObjectParameter("FlightID", flightID) :
                new ObjectParameter("FlightID", typeof(string));
    
            var airplane_NoParameter = airplane_No != null ?
                new ObjectParameter("Airplane_No", airplane_No) :
                new ObjectParameter("Airplane_No", typeof(string));
    
            var tripDateParameter = tripDate.HasValue ?
                new ObjectParameter("TripDate", tripDate) :
                new ObjectParameter("TripDate", typeof(System.DateTime));
    
            var depTimeParameter = depTime.HasValue ?
                new ObjectParameter("DepTime", depTime) :
                new ObjectParameter("DepTime", typeof(System.TimeSpan));
    
            var arrival_TimeParameter = arrival_Time.HasValue ?
                new ObjectParameter("Arrival_Time", arrival_Time) :
                new ObjectParameter("Arrival_Time", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addTrip", flightIDParameter, airplane_NoParameter, tripDateParameter, depTimeParameter, arrival_TimeParameter);
        }
    
        public virtual ObjectResult<string> allTrips()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("allTrips");
        }
    
        public virtual int createTrip(string tripID, string airplane_No, Nullable<System.TimeSpan> deptTime, Nullable<System.TimeSpan> arrivalTime)
        {
            var tripIDParameter = tripID != null ?
                new ObjectParameter("TripID", tripID) :
                new ObjectParameter("TripID", typeof(string));
    
            var airplane_NoParameter = airplane_No != null ?
                new ObjectParameter("Airplane_No", airplane_No) :
                new ObjectParameter("Airplane_No", typeof(string));
    
            var deptTimeParameter = deptTime.HasValue ?
                new ObjectParameter("DeptTime", deptTime) :
                new ObjectParameter("DeptTime", typeof(System.TimeSpan));
    
            var arrivalTimeParameter = arrivalTime.HasValue ?
                new ObjectParameter("ArrivalTime", arrivalTime) :
                new ObjectParameter("ArrivalTime", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("createTrip", tripIDParameter, airplane_NoParameter, deptTimeParameter, arrivalTimeParameter);
        }
    
        public virtual ObjectResult<flightDetails_Result> flightDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<flightDetails_Result>("flightDetails");
        }
    
        public virtual ObjectResult<string> locations()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("locations");
        }
    
        public virtual ObjectResult<string> passengerInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("passengerInfo");
        }
    
        public virtual ObjectResult<planeInfo_Result> planeInfo(string planeID)
        {
            var planeIDParameter = planeID != null ?
                new ObjectParameter("planeID", planeID) :
                new ObjectParameter("planeID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<planeInfo_Result>("planeInfo", planeIDParameter);
        }
    
        public virtual ObjectResult<string> planes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("planes");
        }
    
        public virtual ObjectResult<string> planeSeatInfo(string tripId)
        {
            var tripIdParameter = tripId != null ?
                new ObjectParameter("tripId", tripId) :
                new ObjectParameter("tripId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("planeSeatInfo", tripIdParameter);
        }
    
        public virtual ObjectResult<planeSeats_Result> planeSeats(string plane_no)
        {
            var plane_noParameter = plane_no != null ?
                new ObjectParameter("Plane_no", plane_no) :
                new ObjectParameter("Plane_no", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<planeSeats_Result>("planeSeats", plane_noParameter);
        }
    
        public virtual ObjectResult<SeatPrice_Result> SeatPrice(string tripID)
        {
            var tripIDParameter = tripID != null ?
                new ObjectParameter("TripID", tripID) :
                new ObjectParameter("TripID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SeatPrice_Result>("SeatPrice", tripIDParameter);
        }
    
        public virtual ObjectResult<time_Result> time(string flight)
        {
            var flightParameter = flight != null ?
                new ObjectParameter("Flight", flight) :
                new ObjectParameter("Flight", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<time_Result>("time", flightParameter);
        }
    
        public virtual ObjectResult<TripByID_Result> TripByID(string tripID)
        {
            var tripIDParameter = tripID != null ?
                new ObjectParameter("TripID", tripID) :
                new ObjectParameter("TripID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TripByID_Result>("TripByID", tripIDParameter);
        }
    
        public virtual int alterTrip(string tripID, string airplane_No, Nullable<System.TimeSpan> deptTime, Nullable<System.TimeSpan> arrivalTime)
        {
            var tripIDParameter = tripID != null ?
                new ObjectParameter("TripID", tripID) :
                new ObjectParameter("TripID", typeof(string));
    
            var airplane_NoParameter = airplane_No != null ?
                new ObjectParameter("Airplane_No", airplane_No) :
                new ObjectParameter("Airplane_No", typeof(string));
    
            var deptTimeParameter = deptTime.HasValue ?
                new ObjectParameter("DeptTime", deptTime) :
                new ObjectParameter("DeptTime", typeof(System.TimeSpan));
    
            var arrivalTimeParameter = arrivalTime.HasValue ?
                new ObjectParameter("ArrivalTime", arrivalTime) :
                new ObjectParameter("ArrivalTime", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("alterTrip", tripIDParameter, airplane_NoParameter, deptTimeParameter, arrivalTimeParameter);
        }
    
        public virtual int sp_cancelSeat(string tid)
        {
            var tidParameter = tid != null ?
                new ObjectParameter("tid", tid) :
                new ObjectParameter("tid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_cancelSeat", tidParameter);
        }
    
        public virtual ObjectResult<sp_cancelTicket_Result> sp_cancelTicket(string uid)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_cancelTicket_Result>("sp_cancelTicket", uidParameter);
        }
    
        public virtual int sp_cancelticketStatus(string tid)
        {
            var tidParameter = tid != null ?
                new ObjectParameter("tid", tid) :
                new ObjectParameter("tid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_cancelticketStatus", tidParameter);
        }
    
        public virtual ObjectResult<sp_downloadticket_Result> sp_downloadticket(string bid)
        {
            var bidParameter = bid != null ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_downloadticket_Result>("sp_downloadticket", bidParameter);
        }
    
        public virtual ObjectResult<sp_viewBooking_Result> sp_viewBooking(string uid)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_viewBooking_Result>("sp_viewBooking", uidParameter);
        }
    
        public virtual ObjectResult<proc_getTicket_Result> proc_getTicket(string bid)
        {
            var bidParameter = bid != null ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_getTicket_Result>("proc_getTicket", bidParameter);
        }
    
        public virtual ObjectResult<string> proc_getUserIDbyEmail(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("proc_getUserIDbyEmail", emailParameter);
        }
    
        public virtual ObjectResult<proc_FlightSelect1_Result> proc_FlightSelect1(string from, string to, Nullable<System.DateTime> deptdate, Nullable<System.DateTime> returndate, Nullable<int> passengerCount)
        {
            var fromParameter = from != null ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(string));
    
            var toParameter = to != null ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(string));
    
            var deptdateParameter = deptdate.HasValue ?
                new ObjectParameter("deptdate", deptdate) :
                new ObjectParameter("deptdate", typeof(System.DateTime));
    
            var returndateParameter = returndate.HasValue ?
                new ObjectParameter("returndate", returndate) :
                new ObjectParameter("returndate", typeof(System.DateTime));
    
            var passengerCountParameter = passengerCount.HasValue ?
                new ObjectParameter("PassengerCount", passengerCount) :
                new ObjectParameter("PassengerCount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_FlightSelect1_Result>("proc_FlightSelect1", fromParameter, toParameter, deptdateParameter, returndateParameter, passengerCountParameter);
        }
    
        public virtual int proc_payment(string amount, string status, string bid)
        {
            var amountParameter = amount != null ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var bidParameter = bid != null ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_payment", amountParameter, statusParameter, bidParameter);
        }
    
        public virtual ObjectResult<proc_getpayment_Result> proc_getpayment()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_getpayment_Result>("proc_getpayment");
        }
    
        public virtual ObjectResult<addTripsDetails_Result> addTripsDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<addTripsDetails_Result>("addTripsDetails");
        }
    
        public virtual ObjectResult<sp_cancelTicket1_Result> sp_cancelTicket1(string uid)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_cancelTicket1_Result>("sp_cancelTicket1", uidParameter);
        }
    
        public virtual ObjectResult<string> passengers(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("passengers", idParameter);
        }
    
        public virtual ObjectResult<proc_FlightSelect2_Result> proc_FlightSelect2(string from, string to, Nullable<System.DateTime> deptdate, Nullable<System.DateTime> returndate, Nullable<int> passengerCount)
        {
            var fromParameter = from != null ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(string));
    
            var toParameter = to != null ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(string));
    
            var deptdateParameter = deptdate.HasValue ?
                new ObjectParameter("deptdate", deptdate) :
                new ObjectParameter("deptdate", typeof(System.DateTime));
    
            var returndateParameter = returndate.HasValue ?
                new ObjectParameter("returndate", returndate) :
                new ObjectParameter("returndate", typeof(System.DateTime));
    
            var passengerCountParameter = passengerCount.HasValue ?
                new ObjectParameter("PassengerCount", passengerCount) :
                new ObjectParameter("PassengerCount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_FlightSelect2_Result>("proc_FlightSelect2", fromParameter, toParameter, deptdateParameter, returndateParameter, passengerCountParameter);
        }
    
        public virtual ObjectResult<SearchFlight_Result> SearchFlight(string from, string to, Nullable<System.DateTime> deptdate, Nullable<System.DateTime> returndate, Nullable<int> pass)
        {
            var fromParameter = from != null ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(string));
    
            var toParameter = to != null ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(string));
    
            var deptdateParameter = deptdate.HasValue ?
                new ObjectParameter("deptdate", deptdate) :
                new ObjectParameter("deptdate", typeof(System.DateTime));
    
            var returndateParameter = returndate.HasValue ?
                new ObjectParameter("returndate", returndate) :
                new ObjectParameter("returndate", typeof(System.DateTime));
    
            var passParameter = pass.HasValue ?
                new ObjectParameter("Pass", pass) :
                new ObjectParameter("Pass", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchFlight_Result>("SearchFlight", fromParameter, toParameter, deptdateParameter, returndateParameter, passParameter);
        }
    
        public virtual ObjectResult<SearchFlight1_Result> SearchFlight1(string from, string to, Nullable<System.DateTime> deptdate, Nullable<System.DateTime> returndate, Nullable<int> pass)
        {
            var fromParameter = from != null ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(string));
    
            var toParameter = to != null ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(string));
    
            var deptdateParameter = deptdate.HasValue ?
                new ObjectParameter("deptdate", deptdate) :
                new ObjectParameter("deptdate", typeof(System.DateTime));
    
            var returndateParameter = returndate.HasValue ?
                new ObjectParameter("returndate", returndate) :
                new ObjectParameter("returndate", typeof(System.DateTime));
    
            var passParameter = pass.HasValue ?
                new ObjectParameter("Pass", pass) :
                new ObjectParameter("Pass", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchFlight1_Result>("SearchFlight1", fromParameter, toParameter, deptdateParameter, returndateParameter, passParameter);
        }
    
        public virtual ObjectResult<SearchFlight2_Result> SearchFlight2(string from, string to, Nullable<System.DateTime> deptdate, Nullable<System.DateTime> returndate, Nullable<int> pass)
        {
            var fromParameter = from != null ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(string));
    
            var toParameter = to != null ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(string));
    
            var deptdateParameter = deptdate.HasValue ?
                new ObjectParameter("deptdate", deptdate) :
                new ObjectParameter("deptdate", typeof(System.DateTime));
    
            var returndateParameter = returndate.HasValue ?
                new ObjectParameter("returndate", returndate) :
                new ObjectParameter("returndate", typeof(System.DateTime));
    
            var passParameter = pass.HasValue ?
                new ObjectParameter("Pass", pass) :
                new ObjectParameter("Pass", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchFlight2_Result>("SearchFlight2", fromParameter, toParameter, deptdateParameter, returndateParameter, passParameter);
        }
    }
}
